### ISSUE TITLE
Objetivos do produto - Geral

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-LayoutPropaganda#1]
O objetivo não é o desenvolvimento do produto ou a sua disponibilização. Vcs trazem uma sério de características do produto / solução.

**A pergunta é: QUAL O OBJETIVO DE NEGÓCIO O PRODUTO VAI POTENCIALIZAR OU AUXILIAR A ORNIZAÇÃO A ATINGIR? OU, O QUE SE QUER COM ESSE PRODUTO?**

"O objetivo principal do produto é fornecer por meio de uma aplicação web responsiva o Mídia Kit completo da empresa “Layout Propaganda”, fornecendo aos usuários informações acerca de cada painel incluindo dimensões, localização e audiência; aumentando desta forma a visibilidade dos painéis da empresa para possíveis contratantes. Almeja-se também a integração com a api do Google Maps para fornecer uma experiência mais interativa aos clientes da empresa. Dessa forma, a plataforma permitirá que anunciantes tenham a localização exata de cada painel no mapa contando ainda com filtros avançados que auxiliem em escolhas estratégicas."

**Comment by Vinicius-Muniz** [comment]
Foi adicionado o objetivo principal do nosso produto
