### ISSUE TITLE
Objetivos do produto - Secundários

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-LayoutPropaganda#2]
Aqui, vcs apresentam mais um conjunto de características do produto, quase uma lista de requisitos funcionais. Não é isso.
Reflitam no objetivo geral, e depois quebrem em objetivos menores, secundários.

"Tem-se como objetivo secundário uma área de administração para os funcionários da empresa logarem e a partir desta autenticação, cadastrarem informações de forma mais produtiva, sendo estas: atualizações de fluxo de caixa e atualizações de atributos dos painéis, podendo até adicionar ou remover um painel. Por meio desse fluxo de aplicação, pretendemos simplificar o gerenciamento de operações e o acesso a informações vitais do fluxo de caixa geral e de cada mídia da empresa com interfaces atrativas, modernas e funcionais."

**Comment by Vinicius-Muniz** [comment]
Foi colocado o objetivo secundário do produto, sendo resultado do seu objetivo primário
