### ISSUE TITLE
Organização do projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-LayoutPropaganda#3]
Vcs estão na disciplina de REQ.
Nenhum dos papéis e atribuições apresentadas pela equipe, refere-se aos papéis e atividades de REQ.

![image](https://github.com/mdsreq-fga-unb/2023.2-LayoutPropaganda/assets/68402547/a5f6d558-06e8-4afc-821d-05785037891f)

**Comment by Vinicius-Muniz** [comment]
Foi adicionado o papel de 'Engenheiro de requisitos'
