### ISSUE TITLE
Planejamento das Fases e Iterações do projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-LayoutPropaganda#4]
"No desenvolvimento do sistema Layout Propaganda, a **abordagem utilizada é ÁGIL** por um ciclo de vida iterativo incremental utilizado em uma instância própria do processo unificado."

**ÁGIL + PROCESSO UNIFICADO + ENGENHARIA DE REQUISITOS**
Não entendi o que vcs pensaram qdo produseram isso, mas para mim, não está nada claro. O que dificulta ainda mais pq vcs não falam do processo e não fundamentam.

Outra coisa, na COLUNA de PRODUTO (ENTREGA), vcs colocaram um monte de atividades, e não produtos.

Refaçam essa tabela e revejam o processo que estão propondo.

**Comment by Vinicius-Muniz** [comment]
Mudamos o nosso processo para um que achamos fazer mais sentido no grupo e o detalhamos na sessão de 'processo de desenvolvimento'.
Os produtos das entregas foram colocados na tabela.
